// Generated by gencpp from file drone/Joystick.msg
// DO NOT EDIT!


#ifndef DRONE_MESSAGE_JOYSTICK_H
#define DRONE_MESSAGE_JOYSTICK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace drone
{
template <class ContainerAllocator>
struct Joystick_
{
  typedef Joystick_<ContainerAllocator> Type;

  Joystick_()
    {
    }
  Joystick_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::drone::Joystick_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drone::Joystick_<ContainerAllocator> const> ConstPtr;

}; // struct Joystick_

typedef ::drone::Joystick_<std::allocator<void> > Joystick;

typedef boost::shared_ptr< ::drone::Joystick > JoystickPtr;
typedef boost::shared_ptr< ::drone::Joystick const> JoystickConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drone::Joystick_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drone::Joystick_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace drone

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::drone::Joystick_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drone::Joystick_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone::Joystick_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone::Joystick_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone::Joystick_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone::Joystick_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drone::Joystick_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::drone::Joystick_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::drone::Joystick_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drone/Joystick";
  }

  static const char* value(const ::drone::Joystick_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drone::Joystick_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::drone::Joystick_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drone::Joystick_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Joystick_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drone::Joystick_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::drone::Joystick_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // DRONE_MESSAGE_JOYSTICK_H
