// Generated by gencpp from file drone/Power.msg
// DO NOT EDIT!


#ifndef DRONE_MESSAGE_POWER_H
#define DRONE_MESSAGE_POWER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace drone
{
template <class ContainerAllocator>
struct Power_
{
  typedef Power_<ContainerAllocator> Type;

  Power_()
    : percentage(0.0)
    , power(0.0)  {
    }
  Power_(const ContainerAllocator& _alloc)
    : percentage(0.0)
    , power(0.0)  {
  (void)_alloc;
    }



   typedef float _percentage_type;
  _percentage_type percentage;

   typedef float _power_type;
  _power_type power;





  typedef boost::shared_ptr< ::drone::Power_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drone::Power_<ContainerAllocator> const> ConstPtr;

}; // struct Power_

typedef ::drone::Power_<std::allocator<void> > Power;

typedef boost::shared_ptr< ::drone::Power > PowerPtr;
typedef boost::shared_ptr< ::drone::Power const> PowerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drone::Power_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drone::Power_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::drone::Power_<ContainerAllocator1> & lhs, const ::drone::Power_<ContainerAllocator2> & rhs)
{
  return lhs.percentage == rhs.percentage &&
    lhs.power == rhs.power;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::drone::Power_<ContainerAllocator1> & lhs, const ::drone::Power_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace drone

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::drone::Power_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drone::Power_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone::Power_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone::Power_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone::Power_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone::Power_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drone::Power_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5a30afbd53479ee554e4486fc4c1d0de";
  }

  static const char* value(const ::drone::Power_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5a30afbd53479ee5ULL;
  static const uint64_t static_value2 = 0x54e4486fc4c1d0deULL;
};

template<class ContainerAllocator>
struct DataType< ::drone::Power_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drone/Power";
  }

  static const char* value(const ::drone::Power_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drone::Power_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# information about battery and power consumption\n"
"float32 percentage\n"
"float32 power\n"
;
  }

  static const char* value(const ::drone::Power_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drone::Power_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.percentage);
      stream.next(m.power);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Power_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drone::Power_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drone::Power_<ContainerAllocator>& v)
  {
    s << indent << "percentage: ";
    Printer<float>::stream(s, indent + "  ", v.percentage);
    s << indent << "power: ";
    Printer<float>::stream(s, indent + "  ", v.power);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRONE_MESSAGE_POWER_H
