// Generated by gencpp from file drone/SonarN.msg
// DO NOT EDIT!


#ifndef DRONE_MESSAGE_SONARN_H
#define DRONE_MESSAGE_SONARN_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace drone
{
template <class ContainerAllocator>
struct SonarN_
{
  typedef SonarN_<ContainerAllocator> Type;

  SonarN_()
    : distance(0.0)  {
    }
  SonarN_(const ContainerAllocator& _alloc)
    : distance(0.0)  {
  (void)_alloc;
    }



   typedef float _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::drone::SonarN_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drone::SonarN_<ContainerAllocator> const> ConstPtr;

}; // struct SonarN_

typedef ::drone::SonarN_<std::allocator<void> > SonarN;

typedef boost::shared_ptr< ::drone::SonarN > SonarNPtr;
typedef boost::shared_ptr< ::drone::SonarN const> SonarNConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drone::SonarN_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drone::SonarN_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::drone::SonarN_<ContainerAllocator1> & lhs, const ::drone::SonarN_<ContainerAllocator2> & rhs)
{
  return lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::drone::SonarN_<ContainerAllocator1> & lhs, const ::drone::SonarN_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace drone

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::drone::SonarN_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drone::SonarN_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone::SonarN_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone::SonarN_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone::SonarN_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone::SonarN_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drone::SonarN_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6e77fb10f0c8b4833ec273aa9ac74459";
  }

  static const char* value(const ::drone::SonarN_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6e77fb10f0c8b483ULL;
  static const uint64_t static_value2 = 0x3ec273aa9ac74459ULL;
};

template<class ContainerAllocator>
struct DataType< ::drone::SonarN_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drone/SonarN";
  }

  static const char* value(const ::drone::SonarN_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drone::SonarN_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# the distance between the sensor and the ground\n"
"float32 distance\n"
;
  }

  static const char* value(const ::drone::SonarN_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drone::SonarN_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SonarN_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drone::SonarN_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drone::SonarN_<ContainerAllocator>& v)
  {
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRONE_MESSAGE_SONARN_H
