// Generated by gencpp from file drone/SonarAltitude.msg
// DO NOT EDIT!


#ifndef DRONE_MESSAGE_SONARALTITUDE_H
#define DRONE_MESSAGE_SONARALTITUDE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace drone
{
template <class ContainerAllocator>
struct SonarAltitude_
{
  typedef SonarAltitude_<ContainerAllocator> Type;

  SonarAltitude_()
    : ground_distance(0.0)  {
    }
  SonarAltitude_(const ContainerAllocator& _alloc)
    : ground_distance(0.0)  {
  (void)_alloc;
    }



   typedef float _ground_distance_type;
  _ground_distance_type ground_distance;





  typedef boost::shared_ptr< ::drone::SonarAltitude_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drone::SonarAltitude_<ContainerAllocator> const> ConstPtr;

}; // struct SonarAltitude_

typedef ::drone::SonarAltitude_<std::allocator<void> > SonarAltitude;

typedef boost::shared_ptr< ::drone::SonarAltitude > SonarAltitudePtr;
typedef boost::shared_ptr< ::drone::SonarAltitude const> SonarAltitudeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drone::SonarAltitude_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drone::SonarAltitude_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::drone::SonarAltitude_<ContainerAllocator1> & lhs, const ::drone::SonarAltitude_<ContainerAllocator2> & rhs)
{
  return lhs.ground_distance == rhs.ground_distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::drone::SonarAltitude_<ContainerAllocator1> & lhs, const ::drone::SonarAltitude_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace drone

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::drone::SonarAltitude_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drone::SonarAltitude_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone::SonarAltitude_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone::SonarAltitude_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone::SonarAltitude_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone::SonarAltitude_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drone::SonarAltitude_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8f146d4e34a63c94036de552a9e31ac8";
  }

  static const char* value(const ::drone::SonarAltitude_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8f146d4e34a63c94ULL;
  static const uint64_t static_value2 = 0x036de552a9e31ac8ULL;
};

template<class ContainerAllocator>
struct DataType< ::drone::SonarAltitude_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drone/SonarAltitude";
  }

  static const char* value(const ::drone::SonarAltitude_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drone::SonarAltitude_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# from sonar\n"
"float32 ground_distance\n"
;
  }

  static const char* value(const ::drone::SonarAltitude_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drone::SonarAltitude_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ground_distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SonarAltitude_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drone::SonarAltitude_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drone::SonarAltitude_<ContainerAllocator>& v)
  {
    s << indent << "ground_distance: ";
    Printer<float>::stream(s, indent + "  ", v.ground_distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRONE_MESSAGE_SONARALTITUDE_H
